services:
  back:
    build:
      context: ./back
    container_name: calculator_backend
    working_dir: /back
    volumes:
      - /mnt/c/Users/atgai/WebstormProjects/JS/calculator/back:/app/back:rw
    environment:
      - HOST=back
      - PORT=8000
    ports:
      - "8000:8000"
    networks:
      - communication
  front:
    build:
      context: ./front
    container_name: calculator_frontend
    working_dir: /front
    volumes:
      - /mnt/c/Users/atgai/WebstormProjects/JS/calculator/front:/app/front:rw
    environment:
      - REACT_API_URL="http://back:8000"
    ports:
      - "3000:3000"
    depends_on:
      - back
    networks:
      - communication
networks:
  communication:
    driver: bridge